[package]
name = "sample_criterion"
version = "0.1.0"
authors = ["Ryota Bannai <ryotala0528@gmail.com>"]
edition = "2018"

[[bench]]
name = "benchmark"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.3.3"
