[package]
name = "project"
version = "0.1.0"
authors = ["Ryota Bannai <ryotala0528@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
nix = "0.19.1"
tempfile = "3.2.0"
unicode-segmentation = "1.7.1"
